---
- name: install java
  yum: pkg={{ item }} state=installed
  with_items:
    - java-1.7.0-openjdk

- name: download es
  get_url: url={{ es_url }}/{{ es_rpm }} dest={{ src_dir }}/{{ es_rpm }} mode=0644

- name: install es by yum
  yum: name={{ src_dir }}/{{ es_rpm }} state=installed

- name: ensure elasticsearch is running automatically at boot time
  command: /sbin/chkconfig elasticsearch on

- name: Copy es-config
  template: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml mode=0644
  notify: restart es


- name: Add Plugin elasticsearch-head
  command: /usr/share/elasticsearch/bin/plugin -install mobz/elasticsearch-head


- name: Add Plugin elasticsearch-marvel
  command: /usr/share/elasticsearch/bin/plugin -i elasticsearch/marvel/latest



