---
- name: Copy td.repo
  template: src=td.repo dest=/etc/yum.repos.d/td.repo mode=0644

- name: install by yum
  yum: pkg={{ item }} state=installed
  with_items:
    - td-agent
    - libcurl
    - libcurl-devel
    - gcc

- name: ensure td-agent is running automatically at boot time
  command: /sbin/chkconfig td-agent on

- name: install fluent-plugin-elasticsearch by gem
  command: /usr/lib64/fluent/ruby/bin/fluent-gem install fluent-plugin-elasticsearch

- name: install fluent-plugin-mongo by gem
  command: /usr/lib64/fluent/ruby/bin/fluent-gem install fluent-plugin-mongo

- name: Copy td-agent.conf
  template: src=td-agent.conf dest=/etc/td-agent/td-agent.conf mode=0644 backup=yes
  notify: restart td-agent
